# Generated by Django 2.2.7 on 2020-01-10 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('rel_date', models.DateTimeField(blank=True)),
                ('nicotine', models.FloatField()),
                ('TAR', models.FloatField()),
                ('feel_of_hit', models.CharField(max_length=10)),
                ('score', models.FloatField(default=0)),
                ('isMenthol', models.BooleanField(default=False)),
                ('img', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='goorm_img/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobacco', to='goorm.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('score', models.PositiveIntegerField(default=3)),
                ('tobacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goorm.Tobacco')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
