# Generated by Django 3.0.2 on 2020-01-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('rel_date', models.DateTimeField(blank=True)),
                ('nicotine', models.FloatField()),
                ('TAR', models.FloatField()),
                ('feel_of_hit', models.CharField(max_length=10)),
                ('score', models.FloatField(default=0)),
                ('isMenthol', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobacco', to='goorm.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goorm.Tobacco')),
            ],
        ),
    ]
