# Generated by Django 2.2.7 on 2020-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='isMenthol',
            field=models.BooleanField(default=False),
        ),
    ]
