# Generated by Django 3.0.2 on 2020-01-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobacco', to='goorm.Brand'),
        ),
    ]
