# Generated by Django 2.2.6 on 2020-01-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobacco',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='isMenthol',
            field=models.BooleanField(default=False),
        ),
    ]
