# Generated by Django 2.2.7 on 2020-01-10 08:38

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brd_img',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='brand_img/'),
        ),
    ]
