# Generated by Django 3.0.2 on 2020-01-08 16:19

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0002_auto_20200108_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='img',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='goorm_img/'),
        ),
    ]
