# Generated by Django 2.2.6 on 2020-01-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0002_auto_20200108_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
