# Generated by Django 3.0.2 on 2020-01-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0002_brand_brd_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='rel_date',
            field=models.DateField(blank=True),
        ),
    ]
