# Generated by Django 2.2.7 on 2020-01-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goorm', '0005_auto_20200111_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tobacco',
            name='rel_date',
        ),
    ]
